// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var model;

    model = null;
    return $("#run").click(function() {
      var text;

      text = $('#sample').val();
      $('#sample').change(function() {
        return model = null;
      });
      if (model == null) {
        model = infatuate.learn(text);
      }
      return $('#result').html(model.generate_text(1000));
    });
  });

}).call(this);
